version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_desafio
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
