package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
    "context"
    "fmt"

    "github.com/amichelins/goexpert_clean_arch/internal/infra/graph/model"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input *model.OrderInput) (*model.Order, error) {
    panic(fmt.Errorf("not implemented: CreateOrder - createOrder"))
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context) ([]*model.Order, error) {
    var OrdersModel []*model.Order

    Orders, err := r.ListOrderUseCase.Execute()
    //.OrderRepository.List()

    if err != nil {
        return nil, err
    }
    for _, Order := range Orders {
        //Order.CalculateFinalPrice()
        OrdersModel = append(OrdersModel, &model.Order{ID: Order.ID, Price: Order.Price, Tax: Order.Tax, FinalPrice: Order.FinalPrice})
    }

    return OrdersModel, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) Order(ctx context.Context) (*model.Order, error) {
    panic(fmt.Errorf("not implemented: Order - order"))
}
